### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by jhoon**
It's not a perfect one, but I managed to _add_ the translation to the current one, rather than replacing it completely. Hopefully this can help for other languages... I was looking into other ways of easily managing translated files for static html files, however I ended up going to the adding-new-html-and-assets route until any other strategies are set :)

Hope it helps, thanks for your work!

### CODE REVIEW

**Comment by jhoon** [comment]
This definitely clashes against #12, but I think that one overlooks the image assets, which is another level of complexity when implementing i12n 🤔 

Would love some input from @EatTheRichTextFormat :)

**Comment by EatTheRichTextFormat** [comment]
Nice that so many translations are popping up! Nice work!

Yes, images aren't implemented yet in my branch, but that should be an easy fix. I think the bigger problem is the metadata tags. I still think separating the content from the HTML is the right approach, but maybe a hybrid method is needed: separate files for the metadata for different languages with a common file for the inner div and translations loaded in from JS. I'll be interested to hear what @MKorostoff thinks/if he prefers a "static page"+extra build step approach. What are your thoughts on the matter? Would you be willing to convert your work if my system/some other method is adopted?

**Comment by jhoon** [comment]
Thanks! And to your question: For sure! Whichever approach that ends up being implemented, I would be more than glad to move my changes over there.

I was working under the premise of having the content available to as many people as possible in the shortest time, but improvements are more than welcome, specially if it's to make it easier for more people to contribute.

The separate content for the assets could be a bit tricky, since I found myself editing the svg files to accommodate lengthier text, but that's a problem for the future -just wanted to mention it to keep it in mind later. Great work from you too, @EatTheRichTextFormat!

**Comment by EatTheRichTextFormat** [comment]
> I was working under the premise of having the content available to as many people as possible in the shortest time

Fear not, capitalism will still be here tomorrow :smile:

> The separate content for the assets could be a bit tricky, since I found myself editing the svg files to accommodate lengthier text

I don't see a problem. Yes, the images have to be edited, and the translation file will have to specify which images to replace with the edited versions. Am I overlooking something?

BTW @hmijail, I'm sure you could still help by proof-reading this.

**Comment by hmijail** [comment]
@EatTheRichTextFormat , done in https://github.com/jhoon/1-pixel-wealth/pull/2 

Note however that I am Spanish, and @jhoon seems to be from Peru, so there is a possibility that our Spanish is different enough that it would be better to just have 2 different translation contributions. I will wait for his feedback and we'll see from that.

**Comment by MKorostoff** [comment]
Awesome work! You should go ahead and publish this under your own github account.  See [my comment here](https://github.com/MKorostoff/1-pixel-wealth/issues/8#issuecomment-622964168) for more on this subject.

**Comment by jhoon** [comment]
Awesome, thanks @MKorostoff!

**Comment by jhoon** [comment]
And, by the way, I published the Spanish-Latam version here:
https://jhoon.github.io/1-pixel-wealth/es/

**Pull request closed without merging**
