### PR TITLE
Allow using normal scroll wheel instead dragging the scrollbar

### PR DESCRIPTION
**Pull request by apkoponen**
This visualization is EPIC, but I have only issue with it: Dragging the scrollbar is annoying!

Dragging the scrollbar is annoying, but normal mouse scroll wheels only scroll vertically. We transform all vertical scroll to horizontal scroll in order to fix this.

### CODE REVIEW

**Comment by MKorostoff** [comment]
My knee jerk reaction to this pull request was "no to scrolljacking!" but after testing this a bit, I'm pretty surprised by how natural and performant it feels—so maybe this could be a good solution to the problem. See discussion in #11 for some of the complications around this issue, and other approaches that may work (e.g. remind the user that shift + wheel == horizontal scroll, which most users don't know).

That said, there's two problems with this specific implementation that will prevent me from merging it:

1. Some UI elements _do_ need vertical scrolling (the malaria babies, for instance). This change globally overrides all vertical scrolls, meaning it breaks these elements:

babies

2. It creates hundreds of console errors:

errors

**Comment by apkoponen** [comment]
Oh, sorry for not checking issues properly! I just checked PRs, and saw nothing related.

Based on the discussion in #11 the number of users that this could help is quite small. Also, TIL you can switch to horizontal scroll by pushing shift! :) I'm not confident we could reliably do this change and still allow vertical scroll for some elements without breaking something on some device.

I guess better approach would have some sort of desktop / scrollbar grab detection and show a hint.

Closing this.

**Comment by MKorostoff** [comment]
@apkoponen FYI, I was able to fix the issues I noted above, but it just revealed another larger and more intractable problem. See https://github.com/MKorostoff/1-pixel-wealth/issues/11#issuecomment-623785815. Unfortunately doesn't look like this approach will work—still, thanks for teaching how to do scrolljacking in a way that feels pretty natural. Even though I won't use it on this project, I think I'll probably find a usecase for it eventually in some other project.

**Comment by apkoponen** [comment]
Thank for letting me know! 👌

**Pull request closed without merging**
